# LM Training

NUM_ATTENTION_HEADS = 12
NUM_HIDDEN_LAYERS = 6
OVERWRITE_OUTPUT_DIR = True
LM_TRAIN_EPOCHS = 10
LM_TRAIN_BATCH_SIZE = 32

# Fill Mask

NUM_ROWS_FOR_FILL_MASK = 15000

# Classifier Training

EMBEDDING_DIM = 128
LEARNING_RATE = 1e-3
DROPOUT_RATE = 0.2
HIDDEN_DIM = 64
CLF_TRAIN_EPOCHS = 10
CLF_TRAIN_BATCH_SIZE = 32
